//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthenLightHospital_LA_JC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NLH_Entities : DbContext
    {
        public NLH_Entities()
            : base("name=NLH_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admission> Admission { get; set; }
        public virtual DbSet<Assurance> Assurance { get; set; }
        public virtual DbSet<Departement> Departement { get; set; }
        public virtual DbSet<Lit> Lit { get; set; }
        public virtual DbSet<Medecin> Medecin { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<TypeLit> TypeLit { get; set; }
    }
}
